config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]

  shallow do
    resources :users do
      get 'following', on: :member
      get 'followers', on: :member

      resources :tweets, except: [:index, :new, :edit, :update]
      resource :follows, only: [:create, :destroy]
    end
  end

  # root to: 'pages#home'
  root to: 'pages#root'
  get 'mentions', to: 'pages#mentions'
  get 'search', to: 'pages#search'

  get 'auth/facebook/callback', to: 'sessions#oauth'

  namespace :api, defaults: { format: :json } do
    get 'feed', to: 'pages#feed'
    get 'search', to: 'pages#search'
    get 'mentions', to: 'pages#mentions'
    
    resources :users, only: [:show, :update, :destroy]
    resources :tweets, except: [:index, :new, :edit, :update]
    resource :follows, only: [:create, :destroy]
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  include PgSearch

  belongs_to :user
  has_many :mentions, dependent: :destroy, inverse_of: :tweet
  has_many(
    :mentioned_users,
    through: :mentions,
    source: :mentionable,
    source_type: 'User'
  )

  has_many(
    :mentioned_hashtags,
    through: :mentions,
    source: :mentionable,
    source_type: 'Hashtag'
  )

  validates :body, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  default_scope { order(created_at: :desc) }
  before_validation :parse_for_users, :parse_for_hashtags
  multisearchable against: :body

  def parse_for_users
    mentioned_usernames = self.body.scan(/(?<=@)[^\s\W]*/).uniq

    mentioned_usernames.each do |mentioned_username|
      user = User.find_by_username(mentioned_username)

      unless user.nil?
        self.mentions.new(
          mentionable_id: user.id,
          mentionable_type: 'User'
        )
      end
    end
  end

  def parse_for_hashtags
    mentioned_hashtags = self.body.scan(/(?<=#)[^\s\W]*/).uniq

    mentioned_hashtags.each do |mentioned_hashtag|
      hashtag = Hashtag.find_by_name(mentioned_hashtag) ||
        Hashtag.create!(name: mentioned_hashtag)

      self.mentions.new(
        mentionable_id: hashtag.id,
        mentionable_type: 'Hashtag'
      )
    end
  end

  def display
    display_text = ERB::Util.html_escape(self.body)
    insert_user_links!(display_text)
    insert_hashtag_links!(display_text)
    display_text.html_safe
  end

  def insert_user_links!(display_text)
    self.mentioned_users.each do |mentioned_user|
      display_text.gsub!(
        '@' + mentioned_user.username,
        # When using backbone, include the # in front.
        "<a href='#users/#{mentioned_user.id}'>@#{mentioned_user.username}</a>"
      )
    end
  end

  def insert_hashtag_links!(display_text)
    self.mentioned_hashtags.each do |mentioned_hashtag|
      display_text.gsub!(
        '#' + mentioned_hashtag.name,
        # When using backbone, include the # in front.
        "<a href='#search?query=%23#{mentioned_hashtag.name}'>
          ##{mentioned_hashtag.name}</a>"
      )
    end
  end

end

app/controllers/api/tweets_controller.rb
class Api::TweetsController < ApplicationController
  # before_filter :require_signed_in!

  def show
    @tweet = Tweet.find(params[:id])
    # sleep 2
    render :show
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      render :show
    else
      render json: { errors: @tweet.errors.full_messages }, status: 422
    end
  end

  def destroy
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :require_signed_in!

  def show
    @tweet = Tweet.find(params[:id])
    render :show
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      redirect_to root_url
    else
      flash.now[:errors] = @tweet.errors.full_messages
      render :new
    end
  end

  def destroy
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body, :user_id)
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_preview.html.erb
<article class="tweet-preview clear-fix">
  <section class="tweet-avatar">
    <img class="avatar" src="<%= tweet.user.avatar.url %>">
  </section>

  <section class="tweet-body">
    <h4>
      <a href="<%= user_url(tweet.user) %>">
        <%= tweet.user.name %> @<%= tweet.user.username %>
      </a>
    </h4>
    <small><%= tweet.created_at %></small>
    <p><%= tweet.display %></p>
    <a class="tweet-detail" href="<%= tweet_url(tweet) %>">Details</a>
  </section>
</article>

app/views/tweets/show.html.erb
<main class="tweet-main">
  <header class="clear-fix">
    <section class="tweet-avatar">
      <img class="avatar" src="<%= @tweet.user.avatar.url %>">
    </section>
    
    <section class="tweet-names">
      <h3>
        <a href="<%= user_url(@tweet.user) %>"><%= @tweet.user.name %></a>
      </h3>
      <small>@<%= @tweet.user.username %></small>
    </section>
  </header>
  
  <p class="tweet-body">
    <%= @tweet.display %>
  </p>

  <small><%= @tweet.created_at %></small>
</main>