config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]

  shallow do
    resources :users do
      get 'following', on: :member
      get 'followers', on: :member

      resources :tweets, except: [:index, :new, :edit, :update]
      resource :follows, only: [:create, :destroy]
    end
  end

  # root to: 'pages#home'
  root to: 'pages#root'
  get 'mentions', to: 'pages#mentions'
  get 'search', to: 'pages#search'

  get 'auth/facebook/callback', to: 'sessions#oauth'

  namespace :api, defaults: { format: :json } do
    get 'feed', to: 'pages#feed'
    get 'search', to: 'pages#search'
    get 'mentions', to: 'pages#mentions'
    
    resources :users, only: [:show, :update, :destroy]
    resources :tweets, except: [:index, :new, :edit, :update]
    resource :follows, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include PgSearch
  multisearchable against: [:name, :username]

  has_many :tweets
  has_many :mentions, as: :mentionable, dependent: :destroy
  has_many :followed_follows, class_name: 'Follow', foreign_key: :follower_id
  has_many :follower_follows, class_name: 'Follow', foreign_key: :followed_id

  has_many :mentioned_tweets, through: :mentions, source: :tweet
  has_many :followeds, through: :followed_follows, source: :followed
  has_many :followers, through: :follower_follows, source: :follower
  has_many :followed_tweets, through: :followeds, source: :tweets

  has_attached_file(
    :avatar,
    default_url: "/images/missing:random.png"
  )

  Paperclip.interpolates :random do |attachment, style|
    attachment.instance.id % 5
  end

  validates_attachment_content_type(
    :avatar,
    content_type: /\Aimage\/.*\Z/
  )

  validates :name, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates(
    :username, :email, :session_token,
    presence: true, uniqueness: true
  )
  validate :username_can_only_contain_valid_characters

  def self.find_or_create_by_oauth!(auth_hash)
    user = User.find_by(provider: auth_hash[:provider], uid: auth_hash[:uid])

    unless user.nil?
      return user
    else
      User.create!(
        provider: auth_hash[:provider],
        uid: auth_hash[:uid],
        name: auth_hash[:info][:name],
        email: auth_hash[:info][:email],
        username: auth_hash[:info][:name].gsub(/\s/, '_'), # Will maybe change
        password: SecureRandom::urlsafe_base64
      )
    end
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    (user && user.is_password?(password)) ? user : nil
  end

  attr_reader :password
  after_initialize :ensure_session_token

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def username_can_only_contain_valid_characters
    if self.username =~ /[^a-zA-Z0-9_]/
      errors[:username] << 'Username can only contain letters,
        numbers, and underscores.'
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.includes(
      :mentioned_users,
      :mentioned_hashtags
    ).page(params[:page]).per(15)
    
    @page_number = params[:page] || 1
    @total_pages = @tweets.total_pages
    render :show
  end
  
  def update
    if current_user.update(user_params)
      @user = current_user
      render :show
    else
      render json: { errors: current_user.errors.full_messages }, status: 422
    end
  end

  def destroy
  end

  # def following
  #   user = User.find(params[:id])
  #   @followeds = user.followeds
  #   render :following
  # end
  #
  # def followers
  #   user = User.find(params[:id])
  #   @followers = user.followers
  #   render :followers
  # end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :username, :avatar)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_signed_in!, except: [:show, :new, :create]
  before_filter :require_signed_out!, only: [:new, :create]

  def show
    @user = User.includes(tweets: :mentioned_users).find(params[:id])

    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if current_user.update(user_params)
      flash.now[:notices] = ['Thanks, your settings have been saved.']
    else
      flash.now[:errors] = current_user.errors.full_messages
    end

    render :edit
  end

  def destroy
  end

  def following
    @user = User.find(params[:id])
    @followeds = @user.followeds
    render :following
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
    render :followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :username, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<div class="user-container">
  <header>
    <div class="banner"></div>
    <ul class="clear-fix">
      <li class="avatar-container">
        <img class="follow-avatar avatar" src="<%= user.avatar.url %>">
      </li>
      <li class="follow-button-container">
        <%= render partial: 'users/follow_button', locals: { user: user } %>
      </li>
    </ul>
  </header>

  <main>
    <h3><a href="<%= user_url(user) %>"><%= user.name %></a></h3>
    <small><a href="<%= user_url(user) %>">@<%= user.username %></a></small>
  </main>
</div>

app/views/users/_follow_button.html.erb
<% if current_user.followeds.include?(user) %>
  <form action="<%= user_follows_url(user) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <%= authenticity_token %>
    <button class="unfollow-button blue-button">
      <span>Following</span>
    </button>
  </form>
<% else %>
  <form action="<%= user_follows_url(user) %>" method="POST">
    <%= authenticity_token %>
    <button class="follow-button white-button">Follow</button>
  </form>
<% end %>

app/views/users/_follow_show.html.erb
<div class="follow-container">
  <header>
    <div class="banner"></div>
    <ul class="clear-fix">
      <li class="avatar-container">
        <img class="follow-avatar avatar" src="<%= user.avatar.url %>">
      </li>
      <li class="follow-button-container">
        <%= render partial: 'users/follow_button', locals: { user: user } %>
      </li>
    </ul>
  </header>

  <main>
    <h3><a href="<%= user_url(user) %>"><%= user.name %></a></h3>
    <small><a href="<%= user_url(user) %>">@<%= user.username %></a></small>
  </main>
</div>

app/views/users/_following.html.erb
<header class="user-header-banner"></header>

<header class="user-header clear-fix">
  <ul class="clear-fix">
    <li><a href="<%= user_url(user) %>">TWEETS</a></li>
    <li><a href="<%= following_user_url(user) %>">FOLLOWING</a></li>
    <li><a href="<%= followers_user_url(user) %>">FOLLOWERS</a></li>
    <li>
      <% if user == current_user %>
        <a href="<%= edit_user_url(current_user) %>">Edit profile</a>
      <% else %>
        <%= render partial: 'users/follow_button', locals: { user: @user } %>
      <% end %>
    </li>
  </ul>
</header>

<main class="clear-fix">
  <section class="user-left-section">
    <img class="user-avatar avatar" src="<%= @user.avatar.url %>">

    <h2><%= user.name %></h2>
    <small>@<%= user.username %></small>
  </section>

  <section class="center-section">
    <ul class="users-list clear-fix">
      <% following.each do |follow| %>
        <li>
          <%= render partial: 'users/follow', locals: { user: follow } %>
        </li>
      <% end %>
    </ul>
  </section>
</main>

app/views/users/edit.html.erb
<main class="edit-user clear-fix">
  <section class="left-section">
    <div class="user-card">
      <header class="user-card-banner"></header>
      <main class="user-card-main">
        <%= render partial: 'pages/user_card_info',
          locals: { user: current_user } %>
      </main>
    </div>
  </section>

  <section class="center-section">
    <header>
      <h1>Account</h1>
      <h4>Change your basic account and language settings.</h4>
    </header>

    <main>
      <form action="<%= user_url(current_user) %>"
        method="POST"
        enctype="multipart/form-data"
        class="clear-fix">

        <input type="hidden" name="_method" value="PATCH">
        <%= authenticity_token %>

        <div>
          <label for="edit-username">Username</label>
          <input id="edit-username"
            type="text"
            name="user[username]"
            value="<%= current_user.username %>">
        </div>

        <div>
          <label for="edit-email">Email</label>
          <input id="edit-email"
            type="text"
            name="user[email]"
            value="<%= current_user.email %>">
        </div>

        <div>
          <label for="edit-avatar">Photo</label>
          <input id="edit-avatar" type="file" name="user[avatar]">
        </div>

        <div class="edit-user-button-container">
          <button class="blue-button">Save changes</button>
        </div>
      </form>
    </main>

    <footer>
      <a href="#">Deactivate my account</a>
    </footer>
  </section>
</main>

app/views/users/followers.html.erb
<%= render partial: 'users/following',
  locals: { user: @user, following: @followers } %>

app/views/users/following.html.erb
<%= render partial: 'users/following',
  locals: { user: @user, following: @followeds } %>

app/views/users/index.html.erb
<h2>All Users</h2>

<ul>
  <% @users.each do |user| %>
    <li>
      <a href="<%= user_url(user) %>"><%= user.name %> </a>
      @<%= user.username %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<header class="signed-out-header clear-fix">
  <nav class="clear-fix">
    <div class="logo">logo</div>
    <div class="opposite-logo">
      <a href="<%= new_session_url %>">
        Have an account? <strong>Sign in &#x25BE;</strong>
      </a>
    </div>
  </nav>
</header>

<main class="new-user form-main">

  <h1>Join Twitter today.</h1>

  <form action="<%= users_url %>" method="POST">
    <%= authenticity_token %>

    <label for="sign-up-name">Full name</label>
    <input id="sign-up-name" type="text" name="user[name]">

    <label for="sign-up-email">Email address</label>
    <input id="sign-up-email" type="text" name="user[email]">

    <label for="sign-up-password">Create a password</label>
    <input id="sign-up-password" type="text" name="user[password]">

    <label for="sign-up-username">Choose your username</label>
    <input id="sign-up-username" type="text" name="user[username]">

    <button class="new-user-button">Create my account</button>
  </form>
</main>

app/views/users/show.html.erb
<header class="user-header-banner">
</header>
<header class="user-header clear-fix">
  <ul class="clear-fix">
    <li><a href="#">TWEETS</a></li>
    <li><a href="<%= following_user_url(@user) %>">FOLLOWING</a></li>
    <li><a href="<%= followers_user_url(@user) %>">FOLLOWERS</a></li>
    <li>
      <% if @user == current_user %>
        <a href="<%= edit_user_url(current_user) %>">
          Edit profile
        </a>
      <% else %>
        <%= render partial: 'users/follow_button', locals: { user: @user } %>
      <% end %>
    </li>
  </ul>
</header>

<main class="clear-fix">

  <section class="user-left-section">
    <img class="user-avatar avatar" src="<%= @user.avatar.url %>">

    <h2><%= @user.name %></h2>
    <small>@<%= @user.username %></small>
  </section>

  <section class="center-section">
    <ul class="tweets-list">
      <li class="tweets-list-top clear-fix">
        <h3>Tweets</h3>
        <h3>Tweets & replies</h3>
      </li>
      <% @user.tweets.each do |tweet| %>
        <li>
          <%= render partial: 'tweets/preview', locals: { tweet: tweet } %>
        </li>
      <% end %>
    </ul>
  </section>
</main>