config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]

  shallow do
    resources :users do
      get 'following', on: :member
      get 'followers', on: :member

      resources :tweets, except: [:index, :new, :edit, :update]
      resource :follows, only: [:create, :destroy]
    end
  end

  # root to: 'pages#home'
  root to: 'pages#root'
  get 'mentions', to: 'pages#mentions'
  get 'search', to: 'pages#search'

  get 'auth/facebook/callback', to: 'sessions#oauth'

  namespace :api, defaults: { format: :json } do
    get 'feed', to: 'pages#feed'
    get 'search', to: 'pages#search'
    get 'mentions', to: 'pages#mentions'
    
    resources :users, only: [:show, :update, :destroy]
    resources :tweets, except: [:index, :new, :edit, :update]
    resource :follows, only: [:create, :destroy]
  end
end

app/views/layouts/_errors.html.erb
<ul>
  <% errors.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>

app/views/layouts/_header.html.erb
<header class="signed-in-header">
  <nav class="clear-fix">
    <ul class="left clear-fix">
      <li><a href="#">Home</a></li>
      <li><a href="<%= mentions_url %>">Notifications</a></li>
      <li><a href="#">Discover</a></li>
      <li><a href="#users/<%= current_user.id %>">Me</a></li>
    </ul>

    <ul class="center">
      <li>logo</li>
    </ul>

    <ul class="right clear-fix">
      <li><%= render partial: 'layouts/search' %></li>
      <li><a href="#">Messages</a></li>
      <li><a href="#edit">Settings</a></li>
      <li><%= render partial: 'layouts/sign_out_button' %></li>
      <li>
        <a id="new-tweet" href="#tweets/new">New Tweet</a>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/_new_tweet.html.erb
<div id="new-tweet-modal" class="modal-off">
  <section class="new-tweet-modal-content">
    <header class="new-tweet-header clear-fix">
      <h3>Compose new Tweet</h3>
      <span class="new-tweet-modal-close exit">&times;</span>
    </header>

    <main>
      <form class="new-tweet-form"
        action="<%= user_tweets_url(current_user) %>"
        method="POST">

        <%= authenticity_token %>
        <textarea class="new-tweet-textbox" name="tweet[body]"></textarea>
        <button class="new-tweet-button blue-button">Tweet</button>
      </form>
    </main>
  </section>

  <div class="modal-overlay new-tweet-modal-close"></div>
</div>

app/views/layouts/_notices.html.erb
<ul>
  <% notices.each do |notice| %>
    <li><%= notice %></li>
  <% end %>
</ul>

app/views/layouts/_search.html.erb
<form action="<%= search_url %>" method="GET">
  <input class="search-bar"
    type="text"
    name="query"
    placeholder="Search Twitter"
    value="<%= @query %>">
</form>

app/views/layouts/_sign_out_button.html.erb
<form action="<%= session_url %>" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <%= authenticity_token %>
  <button>Sign out</button>
</form>

app/views/layouts/_tweet_new.html.erb
<div id="new-tweet-modal" class="display-off">
  <section class="new-tweet-modal-content">
    <header class="new-tweet-header clear-fix">
      <h3>Compose new Tweet</h3>
      <span class="new-tweet-modal-close exit">&times;</span>
    </header>

    <main>
      <form class="new-tweet-form"
        action="<%= user_tweets_url(current_user) %>"
        method="POST">

        <%= authenticity_token %>
        <textarea class="new-tweet-textbox" name="tweet[body]"></textarea>
        <button class="new-tweet-button blue-button">Tweet</button>
      </form>
    </main>
  </section>

  <div class="modal-overlay new-tweet-modal-close"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    'application', media: 'all',
    'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application',
    'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <% if signed_in? %>
    <%#= render partial: 'layouts/header' %>
  <% end %>

  <%= render partial: 'layouts/errors',
    locals: { errors: flash[:errors] } if flash[:errors] %>
  <%= render partial: 'layouts/notices',
    locals: { notices: flash[:notices] } if flash[:notices] %>

  <%= yield %>

</body>
</html>